// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA08ixDoTdBIV-pe4e1ApRMiGPaie8CEa8',
    appId: '1:115263332429:web:8da514aa35b0505ad73c04',
    messagingSenderId: '115263332429',
    projectId: 'chat-app-209a3',
    authDomain: 'chat-app-209a3.firebaseapp.com',
    storageBucket: 'chat-app-209a3.appspot.com',
    measurementId: 'G-XZ3MJ445FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmbxq9-1nZAVQDEK_NrnRJCYtFSh_RGV0',
    appId: '1:115263332429:android:aef31036f8b7d7fdd73c04',
    messagingSenderId: '115263332429',
    projectId: 'chat-app-209a3',
    storageBucket: 'chat-app-209a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB52ZqveTXs9F3KjpqfdyF2_8dDlzlAdC0',
    appId: '1:115263332429:ios:d772e702cadb0cc8d73c04',
    messagingSenderId: '115263332429',
    projectId: 'chat-app-209a3',
    storageBucket: 'chat-app-209a3.appspot.com',
    iosClientId: '115263332429-nloneg4oaevsn20862f57kagiqbmi624.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB52ZqveTXs9F3KjpqfdyF2_8dDlzlAdC0',
    appId: '1:115263332429:ios:d772e702cadb0cc8d73c04',
    messagingSenderId: '115263332429',
    projectId: 'chat-app-209a3',
    storageBucket: 'chat-app-209a3.appspot.com',
    iosClientId: '115263332429-nloneg4oaevsn20862f57kagiqbmi624.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
